version: '3'
services:
#  db:
#    container_name: "nha-db"
#    image: mysql:5.7.28
#    env_file:
#      - ./nha-init/env.properties
#    volumes:
#      - ./mysql-storage/:/var/lib/mysql/
#      - ./nha-db/:/docker-entrypoint-initdb.d/
#    ports:
#      - "3306":"3306"
  
  nha:
    container_name: "nha-app"
    build: .
    volumes:
      - ./nha-init/:/docker-entrypoint-initnha.d/
#    depends_on:
#      - db
    image: nhareg:latest
    entrypoint: /docker-entrypoint-initnha.d/entrypoint.sh
    ports:
      - 9990:9990
      - 8080:8080
      - 8443:8443

#networks:
#  default:
#    driver: bridge